### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [vlaube-de/7min-workout#1]
Hey there!

I was wondering what license, if any, you make the script available in.

I'm trying to package it for my personal use and the packaging platform requires me to specify a license.

**Comment by vlenhart** [comment]
fixed by adding a license file for the MIT license.

@rnkn: tell me if you have a problem with this change because it also affects your contribution to the project

**Comment by rnkn** [comment]
Yep cool.

**Comment by peanutbutterandcrackers** [comment]
Thank you. I have updated the [package definition](https://github.com/peanutbutterandcrackers/guix-packages/blob/master/workout.scm) accordingly.
